core/advert/urls.py
from django.urls import path
from . import views
app_name = 'advert'

urlpatterns = [
    path('', views.index,name= "index"),
    path('myadvert/', views.myadvert,name= "myadvert"),
    path('addadvert/', views.addadvert,name= "addadvert"),
    path('advertdetail/<int:id>/', views.advertdetail, name='advertdetail'),
    path('update/<int:id>/', views.update,name= "update"),   
    path('delete/<int:advert_id>/', views.delete, name='delete')
]

core/api/urls.py
from django.contrib import admin
from django.urls import path
from . import views






app_name= "api"



urlpatterns = [

    path('register/', views.registerUser, name="register"),
    path('login/', views.MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('logout/', views.LogoutView.as_view(), name='user-logout'),

    path('profile/', views.getUserProfile, name="users-profile"),
    path('profile/update', views.updateUserProfile, name="users-profile-update"),
    path('', views.getUsers, name="users"),
    path('<str:pk>/', views.getUserById, name='user'),
    path('update/<str:pk>/', views.updateUser, name='user-update'),
    
    path('advert/', views.AdvertList.as_view(), name='advert-list'),
    path('advert/<int:pk>/', views.AdvertDetail.as_view(), name='advert-detail'),
    path('addadvert/', views.AddAdvertisement.as_view(), name='add-advert'),

]

core/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.chat_index, name='chat_index'),
    path('<int:advert_id>/<int:user_id>/', views.chat_room, name='chat_room'),
    path('inbox/', views.inbox, name='inbox'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path,include
from advert import views
from user import views
from event import views
from chat import views
from django.conf import settings
from django.conf.urls.static import static
from advert import views
from api import views
from .views import index

app_name = 'core'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index,name= "index"),
    path('user/', include("user.urls")),
    path('event/', include("event.urls")), 
    path('advert/', include("advert.urls")),
    path('api/', include("api.urls")),
    path('chat/', include("chat.urls")),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import profile
app_name= "user"

urlpatterns = [
    path('register/', views.register,name= "register"),
    path('login/', views.loginUser,name= "login"),
    path('logout/', views.logoutUser,name= "logout"),
    path('profile/<int:id>/', views.profile,name= "profile"),
    path('profile_edit/', views.profile_edit, name='profile_edit'),

]

core/templates/includes/advertcard.html
<div class="col-md-3">
    <div class="product-single-card">
      <div class="product-top-area">
        <div class="product-img">
          <div class="first-view">
            <img src="{{advert.event.image_url}}" alt="logo" class="img-fluid" onerror="this.src='https://i.ibb.co/qpB9ZCZ/placeholder.png'">
          </div>
        </div>
        <div class="sideicons">

          {% if request.user.is_authenticated %}
            <a href="{% url 'chat:chat_room' advert.id request.user.id %}" class="sideicons-btn">
              <i class="fa-solid fa-message"></i>
            </a>
          {% else %}
            <a href="{% url 'user:login' %}" class="sideicons-btn">
              <i class="fa-solid fa-message"></i>
            </a>
          {% endif %}

          <a href="{% url 'advert:advertdetail' advert.id %}" class="sideicons-btn">
              <i class="fa-solid fa-eye"></i>
          </a>
          
        </div>
      </div>
      <div class="product-info">
        <div class="d-flex justify-content-between">
            <h6 class="product-category"><span>{{advert.event.city}}</span></h6>
            <h6 class="product-category"><span>{{advert.event.start_time|date:'d.m.Y'}}</span></h6>
        </div>
        
        <h6 class="product-title text-truncate"><a href="{% url 'advert:advertdetail' advert.id %}">{{advert.event.title}}</a></h6>
        <span>{{advert.event.location}}</span>
        <div class="d-flex justify-content-end align-items-center">


          

          <div class="d-flex align-items-center ml-auto">
            <a href='{% url 'user:profile' advert.author.id %}' class="mx-1" >@{{advert.author.username}}</a>
            <img  class="rounded-circle mx-1 navbar-profile-photo" src="{% if user.profile_photo %}{{ user.profile_photo.url }}{% else %}/media/profile_photos/DefaultProfileIcon.png{% endif %}" height="25" alt="">

          </div>
        </div>
        <div class="d-flex flex-wrap align-items-center py-2">
          <div class="new-price text-success">
            {{advert.price}} TL
          </div>

        </div>
      </div>
    </div>
  </div>

core/templates/includes/chatmessage.html
<div class="mx-1 my-1 chat-message bg-secondary rounded">
    <div class="d-flex align-items-center">
        <img src="https://mdbootstrap.com/img/new/avatars/2.jpg" alt="Kullanıcı Adı" class="rounded-circle" style="width: 40px; height: 40px; margin-right: 10px;">
        <strong class="mr-auto">USERNAME</strong>
        <small class="">TIME</small>
    </div>
    <p class="mb-2" style="margin-left: 50px;">MESSAGE CONTENT</p>
</div>

core/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-5 ">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>
    <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'index' %}">
      EtkinlikPass
    </a>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      
        <ul class="navbar-nav">
          <li class="nav-item">
            <a class="nav-link active mx-3" href="{% url 'index' %}">Anasayfa</a>
          </li>
          {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active mx-3" href="{% url 'advert:addadvert' %}">İlan Ekle</a>

          </li>
          {% endif %}
        </ul>
      <!-- Search Form -->


        <form action="{% url 'index' %}" method="get" class="d-flex form-inline mx-auto pt-3">
          <input class="form-control" type="text" name="keyword" placeholder="İlanlarda ara...">
          <button class="btn btn-outline-primary" type="submit">Ara</button>
        </form>

        

    </div>
    {% if request.user.is_authenticated %}
     <div class="d-flex align-items-center">
      <div class="dropdown">
        <a class="text-reset me-3" href="{% url 'chat:inbox' %}" style="text-decoration: none;">
          <i class="fas fa-bell"></i>
          <span class="badge rounded-pill badge-notification bg-danger">{{ unread_message_count }}</span>
        </a>
      </div>
      <div class="dropdown">
        <a id="navbarDropdownMenuLink2" class="text-reset me-3 dropdown-toggle hidden-arrow" href="#" role="button" data-toggle="dropdown" aria-expanded="false" style="text-decoration: none;">
          <img class="navbar-profile-photo" src="{% if user.profile_photo %}{{ user.profile_photo.url }}{% else %}/media/profile_photos/DefaultProfileIcon.png{% endif %}" alt="Kullanıcı Profil Fotoğrafı">

        </a>
        <ul class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink2">
          <li><a class="dropdown-item" href='{% url 'user:profile' request.user.id %}'>Profilim</a></li>
          <li><a class="dropdown-item" href="{% url 'advert:myadvert' %}">İlanlarım<span class="sr-only">(current)</span></a></li>
          <li><a class="dropdown-item" href="{% url 'user:logout' %}">Çıkış Yap</a></li>
        </ul>
      </div>
    </div>
    {% else %}

    <div class="btn-group" role="group" aria-label="Giriş ve Kaydol">
      
        <a class="btn" href="{% url 'user:register' %}">
          <i class="fa fa-user-plus px-2"></i> <span class="icon-text">Kaydol</span>
        </a>
      
        <a class="btn" href="{% url 'user:login' %}">
          <i class="fa fa-sign-in px-2"></i> <span class="icon-text">Giriş Yap</span>
        </a>
    </div>
    
    
    {% endif %}
    
  </div>
</nav>