core/advert/urls.py
from django.urls import path
from . import views
app_name = 'advert'

urlpatterns = [
    path('', views.index,name= "index"),
    path('myadvert/', views.myadvert,name= "myadvert"),
    path('addadvert/', views.addadvert,name= "addadvert"),
    path('advertdetail/<int:id>/', views.advertdetail, name='advertdetail'),
    path('update/<int:id>/', views.update,name= "update"),   
    path('delete/<int:advert_id>/', views.delete, name='delete')
]

core/api/urls.py
from django.contrib import admin
from django.urls import path
from . import views






app_name= "api"



urlpatterns = [

    path('register/', views.registerUser, name="register"),
    path('login/', views.MyTokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('logout/', views.LogoutView.as_view(), name='user-logout'),

    path('profile/', views.getUserProfile, name="users-profile"),
    path('profile/update', views.updateUserProfile, name="users-profile-update"),
    path('', views.getUsers, name="users"),
    path('<str:pk>/', views.getUserById, name='user'),
    path('update/<str:pk>/', views.updateUser, name='user-update'),
    
    path('advert/', views.AdvertList.as_view(), name='advert-list'),
    path('advert/<int:pk>/', views.AdvertDetail.as_view(), name='advert-detail'),
    path('addadvert/', views.AddAdvertisement.as_view(), name='add-advert'),

]

core/chat/urls.py
from django.urls import path
from . import views

app_name = 'chat'

urlpatterns = [
    path('', views.chat_index, name='chat_index'),
    path('<int:advert_id>/<int:user_id>/', views.chat_room, name='chat_room'),
    path('inbox/', views.inbox, name='inbox'),
]

core/core/urls.py
from django.contrib import admin
from django.urls import path,include
from advert import views
from user import views
from event import views
from chat import views
from django.conf import settings
from django.conf.urls.static import static
from advert import views
from api import views
from .views import index

app_name = 'core'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index,name= "index"),
    path('user/', include("user.urls")),
    path('event/', include("event.urls")), 
    path('advert/', include("advert.urls")),
    path('api/', include("api.urls")),
    path('chat/', include("chat.urls")),
]  + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/user/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from .views import profile
app_name= "user"

urlpatterns = [
    path('register/', views.register,name= "register"),
    path('login/', views.loginUser,name= "login"),
    path('logout/', views.logoutUser,name= "logout"),
    path('profile/<int:id>/', views.profile,name= "profile"),
    path('profile_edit/', views.profile_edit, name='profile_edit'),

]

core/advert/forms.py
from django import forms 
from .models import Advert, DeleteReason
from event.models import Event 


class AdvertForm(forms.ModelForm):
    event = forms.ModelChoiceField(
        queryset=Event.objects.all(),
        widget=forms.Select(attrs={'class': 'select2', 'style': 'width: 100%;'}),
        label='Etkinlik:'
    )
    seller_description = forms.CharField(
        widget=forms.Textarea(attrs={'class': 'form-control'}),
        label='Açıklama:'
    )
    price = forms.IntegerField(
        widget=forms.NumberInput(attrs={'class': 'form-control'}),
        label='Fiyat:'
    )

    class Meta:
        model = Advert
        fields = ['event', 'seller_description', 'price']





class DeleteReasonForm(forms.ModelForm):
    class Meta:
        model = DeleteReason
        fields = ['reason']



class ReportAdvertForm(forms.Form):
    CHOICES = [
        ('overpriced', 'Fiyat piyasasının üzerinde'),
        ('offensive', 'İlan hakaret içeriyor'),
        ('deceptive', 'Aldatıcı ilan'),
        ('other', 'Diğer'),
    ]
    reason = forms.ChoiceField(choices=CHOICES, required=True)
    additional_info = forms.CharField(widget=forms.Textarea, required=False)

core/templates/addadvert.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block head %}
<link rel="stylesheet" href="{% static 'css/advertdetail.css' %}">
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/css/select2.min.css" rel="stylesheet" />
{% endblock %}

{% block body %}
<div class="d-flex justify-content-center row">
    <div class="w-75">
        <h2>Eklemek istediğiniz etkinliğin bilgilerini giriniz, <small>{{request.user.username}} </small></h2>  <hr>

        <form method="post" id="advertForm">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-primary">İlan Oluştur</button>
        </form>
    </div>
</div>

{% endblock %}

core/templates/advertdetail.html
{% extends 'layout.html' %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/advertdetail.css' %}">
{% endblock head %}

{% block body %}


<div id="main-content">
        <div class="container">
            <div class="row clearfix">
                <div class="col-lg-8 col-md-12 left-box">
                    <div class="card single_post">
                        <div class="body">
                            <div class="img-post">
                                <img class="" src="{{advert.event.image_url}}">
                            </div>
                            <h3>{{advert.event.title}}</h3>
                            <span>{{advert.event.start_time}}</span>
                            <p>{{ advert.event.description|safe }}</p>
                        </div>
                    </div>

                    <div class="card">
                        <div class="d-flex flex-column justify-content-center align-items-center header">
                            <p>Bu etkinliğe ait bileti aşağıdaki butona tıklayarak resmi satıcıdan görüntüleyebilirsiniz.</p>
                            <div class="mt-2">
                                <button onclick="location.href='{{advert.event.ticket_url}}';">
                                    <i class="fa fa-ticket"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-12 right-box">

                    {% if request.user.is_authenticated %}
                    {% if request.user.id == advert.author.id %}
                            <div class="card">
                                <div class="d-flex flex-column justify-content-center align-items-center header">
                                    <div class="mt-2">
                                        <button onclick="location.href='{% url 'advert:update' advert.id %}';">
                                            <i class="fa fa-edit"></i>
                                        </button>

                                        <button onclick="location.href='{% url 'advert:delete' advert.id %}';">
                                            <i class="fa fa-trash"></i>
                                        </button>
                                    </div>
                                </div>
                            </div>
                        {% endif %}
                    {% endif %}



                    <div class="card">
                        <div class="d-flex flex-column justify-content-center align-items-center header">
                            <h2 class="mb-2 text-success">{{advert.price}} TL</h2>
                            <p>{{advert.seller_description}}</p>

                            {% if advert.author != current_user %} 
                            <div class="mt-2 d-flex align-items-center gap-2">

                                {% if request.user.is_authenticated %}

                                        <a href='{% url 'chat:chat_room' advert.id request.user.id %}'>
                                            <button class="{% if advert.author is current_user %} disabled {% endif %}">
                                                <i class="fa-solid fa-message"></i>
                                            </button>
                                        </a>
                                    
                                {% else %}
                                <a href='{% url 'user:login' %}'>
                                    <button>
                                        <i class="fa-solid fa-message"></i>
                                    </button>
                                </a>
                                {% endif %}
                                {% if request.user.is_authenticated %}
                                <form method="post" action="{% url 'advert:advertdetail' advert.id %}">
                                    {% csrf_token %}

                                    {% if advert in user.favorites.all %}
                                        <button type="submit" name="favorite" class="mt-3">
                                            <i class="fa fa-heart"></i>
                                        </button>
                                    {% else %}
                                        <button type="submit" name="favorite" class="mt-3">
                                            <i class="far fa-heart" aria-hidden></i>
                                        </button>
                                    {% endif %}
                                </form>
                                <button type="button" data-toggle="modal" data-target="#reportModal">
                                    <i class="fa-solid fa-flag"></i>
                                </button>
                            </div>

                            {% else %}
                            <a href='{% url 'user:login' %}'>
                                <button>
                                    <i class="far fa-heart"></i>
                                </button>
                            </a>
                            {% endif %}
                            {% endif %}
                        </div>
                    </div>

                    <div class="modal fade" id="reportModal" tabindex="-1" role="dialog" aria-labelledby="reportModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="reportModalLabel">İlanı Şikayet Et</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    <form method="post" id="reportForm">
                                        {% csrf_token %}
                                        <div class="form-group">
                                            <label for="id_reason">Şikayet Nedeni:</label>
                                            {{ report_form.reason }}
                                        </div>
                                        <div class="form-group">
                                            <label for="id_additional_info">Ek Bilgi:</label>
                                            {{ report_form.additional_info }}
                                        </div>
                                    </form>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Kapat</button>
                                    <button type="button" class="btn btn-danger" onclick="document.getElementById('reportForm').submit();">Şikayet Et</button>
                                </div>
                            </div>
                        </div>
                    </div>
                    


                    

                    <div class="card">
                        <div class="d-flex flex-column justify-content-center align-items-center header">
                            <span class="mb-2">{{advert.event.city}}</span>
                            <span class="mb-2">{{advert.event.location}}</span>
                            <span class="mb-2">{{advert.event.start_time|date:'d.m.Y H:i'}}</span>
                        </div>
                    </div>

                    <div class="d-flex flex-column justify-content-center align-items-md-center card p-4">

                        {% if advert.author.profile_photo %}
                            <img class="rounded-circle navbar-profile-photo" src="{{ advert.author.profile_photo.url }}">
                        {% else %}
                            <img class="rounded-circle navbar-profile-photo" src="/media/profile_photos/DefaultProfileIcon.png">
                        {% endif %}


                    
                        <a href="{% url 'user:profile' advert.author.id %}" style="font-size: x-large;">{{advert.author.username}}</a>


                    </div>
                </div>
            </div>

        </div>

{% endblock %}

core/templates/delete_advert.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block body %}
<div class="card login-form py-5">
    <div class="body col-md-6 offset-md-3 px-5">
        <div class="header d-flex flex-row justify-content-center">
            <form method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit">İlanı Sil</button>
            </form>
            
        </div>
    </div>
</div>

{% endblock  %}

core/templates/index.html
{% extends 'layout.html' %}

{% block body %}

{% if request.user.is_authenticated %}
<div class="container">
    <div class="px-4">
    <h2>Hoş geldin, {{request.user.username}}</h2>
    </div>
</div>

{% endif %}

<section>
    <div class="container">
      <div class="row g-4 py-5">

        {% if not all_adverts or undeleted_adverts_count == 0 %}

          {% if keyword %}

            <div class="col-md-12">
              <div class="alert alert-danger" role="alert">
                <h4 class="alert-heading">Uyarı!</h4>
                <p>Aradığınız kriterlere uygun ilan bulunamadı.</p>
                <hr>
                {% if request.user.is_authenticated %}
                <p class="mb-0">İlan yayınlamak için <a href="{% url 'advert:addadvert' %}">buraya</a> tıklayın.</p>
                {% else %}
                <p class="mb-0">İlan yayınlamak için <a href="{% url 'user:login' %}">buraya</a> tıklayın.</p>
                {% endif %}
                
            </div>

          {% else %}

            <div class="col-md-12">
              <div class="alert alert-danger" role="alert">
                <h4 class="alert-heading">Uyarı!</h4>
                <p>Henüz hiçbir ilan yayınlanmamış.</p>
                <hr>
                {% if request.user.is_authenticated %}
                <p class="mb-0">İlan yayınlamak için <a href="{% url 'advert:addadvert' %}">buraya</a> tıklayın.</p>
                {% else %}
                <p class="mb-0">İlan yayınlamak için <a href="{% url 'user:login' %}">buraya</a> tıklayın.</p>
                {% endif %}
                
            </div>

          {% endif %}

        {% else %}

        {% for advert in all_adverts %}

            {% if not advert.is_deleted %}

              {% include "includes/advertcard.html" %}

            {% endif %}
        
        {% endfor %}

        {% endif %}

      </div>
    </div>
  </section>
{% endblock  %}

core/templates/layout.html
{% load static %}

<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/css/all.min.css" integrity="sha512-z3gLpd7yknf1YoNbCzqRKc4qyor8gaKU1qmn+CShxbuBusANI9QpRohGBreCFkKxLhei6S9CQXFEbbKuqLg0DA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/custom.css' %}">

    {% block head %}

    {% endblock head %}

    <title>EtkinlikPass</title>

</head>
<body> <div class="container">
   {% include "includes/navbar.html" %}
   

    {% if messages %}

            {% for message in messages %}
            {% if message.tags == "info" %}
            <div class="alert alert-danger">{{ message }}</div>
            {% else %}
            <div class="alert alert-{{ message.tags }}">{{ message }}</div>

            {% endif %}


            {% endfor %}

        {% endif %}

    {% block body %}

    {% endblock body %}



<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.2/js/all.min.js" integrity="sha512-uKQ39gEGiyUJl4AI6L+ekBdGKpGw4xJ55+xyJG7YFlJokPNYegn9KwQ3P8A7aFQAUtUsAQHep+d/lrGqrbPIDQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

<script>
  $(document).ready(function() {
      $('.select2').select2();
  });

</script>

</body>
</html>

core/templates/login.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block body %}
<div class="card login-form py-5">
    <div class="body col-md-6 offset-md-3 px-5">
        <div class="header d-flex flex-row justify-content-center">
            <span><h2 class="mb-5">Giriş Yap</h2></span>
        </div>
        <div class="">
            <form method="post">
                
                {% csrf_token %}
                {{ form|crispy }}

                <div class="d-flex flex-row justify-content-between text-start my-3">
                    <span class=""><a href="{% url 'user:register' %}" class="mb-5">Şifremi unuttum</a></span>
                    <span class="">Hesabın yok mu? <a href="{% url 'user:register' %}">Kaydol</a></span>
                </div>
                <div class="d-flex flex-row justify-content-center align-items-center">
                    <button type="submit" class="mt-2">Giriş Yap</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock  %}

core/templates/myadvert.html
{% extends 'layout.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/advertdetail.css' %}">
{% endblock head %}

{% block body %}
<div class="d-flex justify-content-center row">
    <div class="w-75">

        <h2>İlanlarım</h2> 
        {% if form  %}
        <table class="table">
                <thead>
                <tr>
                    <th scope="col"></th>
                    <th scope="col">Etkinlik</th>
                    <th scope="col">Fiyat</th>
                    <th scope="col">Tarih</th>
                    <th scope="col">Yer</th>
                    <th scope="col">Güncelle</th>
                    <th scope="col">Sil</th>
                    <th scope="col">Silinme Tarihi</th>
                </tr>
                </thead>
                <tbody>
                {% for advert in form  %}
                <tr>
                    <th scope="row"><a href="{% url 'advert:advertdetail' advert.id %}"><img src="{{advert.event.image_url}}" width="100"></a></th>
                    <th scope="row"><a href="{% url 'advert:advertdetail' advert.id %}">{{advert.event.title}}</a></th>
                    <td scope="row" class="text-success">{{advert.price}} TL</td>
                    <td>{{advert.event.start_time}}</td>
                    <td>{{advert.event.city}}</td>
                    <td><a href="{% url 'advert:update' advert.id %}" class="btn btn-danger {% if advert.is_deleted %} disabled {% endif %}">Güncelle</a></td>                      
                    <td><a href="{% url 'advert:delete' advert.id %}" class = "btn btn-danger {% if advert.is_deleted %} disabled {% endif %}">Sil</a> </td>
                    <td>{% if advert.is_deleted %} {{advert.deleted_at}} {% else %} - {% endif %} </td>

                    {% comment %} <td><a href="/advert/update/{{advert.id}}" class = "btn btn-danger">Güncelle</a></td>
                    <td><a href="/advert/delete/{{advert.id}}" class = "btn btn-danger">Sil</a> </td> {% endcomment %}

                </tr>
                {% endfor %}

                </tbody>
            </table>
        {% else %}


        <div class = "alert alert-danger">
            Henüz bir ilanınız bulunmuyor...

        </div>
        {% endif %}

            <br>
            <a href="/advert/addadvert">
                <button>İlan Ekle</button>
            </a> 

    </div>
</div>

{% endblock  %}

core/templates/profile.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<link rel="stylesheet" href="{% static 'css/advertdetail.css' %}">


<style>
  .profile-image-container {
    width: 250px;
    height: 250px;
    overflow: hidden;
    display: flex;
    justify-content: center;
    align-items: center;
}

.profile-image-container img {
    height: auto;
    width: 50%;
    min-width: 250px;
    object-fit: cover;
}
</style>


{% endblock %}

{% block body %}
<div class="container">
    <hr>
    <div class="row align-items-stretch">

        <div class="col-md-4 d-flex">
          <div class="align-self-stretch w-100 profile-image-container">
              {% if profile_user.profile_photo %}
                  <img src="{{ profile_user.profile_photo.url }}" class="img-fluid" alt="Profile Image">
              {% else %}
                  <img src="/media/profile_photos/DefaultProfileIcon.png" class="img-fluid" alt="Default Profile Image">
              {% endif %}
          </div>                      
        </div>
    
        <div class="col-md-8 d-flex">
            <div class="align-self-stretch w-100">
                <div class="d-flex flex-column justify-content-between h-100">
                    <h3>{{ profile_user.username }}</h3>

                    {% if request.user.is_authenticated and profile_user.id == request.user.id %} 
                    <p>{{ profile_user.email }}</p>
                    {% endif %}

                    <p>{{ profile_user.first_name }} {{ user.last_name }}</p>
                    <p>{{ profile_user.city }}</p>

                    {% if request.user.is_authenticated and profile_user.id == request.user.id %} 
                        <a class="mt-auto" href="{% url 'user:profile_edit' %}"><button>Profil Güncelle</button></a>
                    {% endif %} 

                </div>
            </div>
        </div>
    </div>

    <hr class="my-3">
    

    {% if request.user.is_authenticated and profile_user.id == request.user.id %}
    <div class="row">
        <h3 class="my-3">Favori İlanlarım</h3>
        {% for advert in profile_user.favorites.all %}
          <div class="col-md-4 col-lg-3 mb-4">
            <div class="card">
              <a href="{% url 'advert:advertdetail' advert.id %}"><img src="{{ advert.event.image_url|default:'/media/default-image.png' }}" class="card-img-top" alt="{{ advert.event.title }}" style="height: 150px; object-fit: cover; background-color: #8B4513;"></a>
              
              <div class="card-body d-flex flex-column">
                <a href="{% url 'advert:advertdetail' advert.id %}"><h5 class="card-title text-danger">{{ advert.event.title|truncatewords:3 }}</h5></a>
                
                <div class="d-flex justify-content-between align-items-center">
                  <p class="card-text text-muted my-2">{{ advert.event.start_time|date:"d M Y H:i" }}</p>
                  <p class="card-text text-success">{{ advert.price|default:'0' }} TL</p>
                </div>
              </div>
            </div>
          </div>
        {% empty %}
          <p class="text-center">Favori ilanınız bulunmamaktadır.</p>
        {% endfor %}
    {% endif %}

</div>
{% endblock %}

core/templates/profile_edit.html
{% extends 'layout.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block head %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock %}

{% block body %}
<div class="container">
    <h2>Kullanıcı Profili Duzenleme</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Güncelle</button>
    </form>
</div>
{% endblock %}

core/templates/update.html
{% extends "layout.html" %}

{% load crispy_forms_tags %}

{% block body %}

<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <h3 class="mb-3">İlan Güncelle</h3>
            <form method="post" enctype="multipart/form-data" action="{% url 'advert:update' id %}">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">İlanı Güncelle</button>
            </form>
        </div>
    </div>
</div>

{% endblock body %}